"EffectList"
{
	"Info"
	{
		"CategoryName" "Garry's Modular Combat"
	
		"EffectOptions"
		{
			"Color255"
			"
			critgun_weaponmodel_colorable
			critgun_weaponmodel_colorable_glow
			peejar_drips_colorable
			"
			"StandardEffects"
			"
			onfire
			healing_effect
			healing_drips
			teleported_flash
			teleportedin_blue
			teleportedin_elecblue
			teleportedin_green
			teleportedin_neutral
			teleportedin_orange
			teleportedin_pink
			teleportedin_purple
			teleportedin_red
			teleportedin_white
			teleportedin_yellow
			"
		}
	}

"gmc_particles.pcf"
"
critgun_weaponmodel_colorable
critgun_weaponmodel_colorable_glow
peejar_drips_colorable
healing_effect
healing_drips
onfire
teleportedin_blue
teleportedin_elecblue
teleportedin_green
teleportedin_neutral
teleportedin_orange
teleportedin_pink
teleportedin_purple
teleportedin_red
teleportedin_white
teleportedin_yellow
"
}